разметка главной страницы
htmlacademy-adaptive/1473197-cat-energy-22 pull request #2
Opened 2021-03-28 14:34 UTC by LianaBazhenova

2021-03-28 17:39 UTC, ant1quar requested changes

2021-03-28 17:39 UTC, ant1quar commented on source/index.html
> +      </a>
Молодец, что вынесла мобильное лого отдельно. Но, судя по макетам там три логотипа
1) на десктопе и планшете - текст и логотип это одна картинка
2) на телефоне две отдельных картинки и логотип другой

2021-03-28 17:39 UTC, ant1quar commented on source/index.html
> +          <ul class="main-nav__list">
много оберток класс `main-nav__wrapper` можно навесить прямо на `ul`

2021-03-28 17:39 UTC, ant1quar commented on source/index.html
> +        <div class="hero-header__wrapper">
Фоновую картинку на зеленом фоне через background задашь?

2021-03-28 17:39 UTC, ant1quar commented on source/index.html
> +            </li>
тут пропущены цифры, которые есть на планшете и десктопе

2021-03-28 17:39 UTC, ant1quar commented on source/index.html
> +            </div>
не хватает зеленого прогрессбара посередине

2021-03-28 17:39 UTC, ant1quar commented on source/index.html
> +            </div>
Интересно, а они пробовали просто кота не кормить?

2021-03-28 17:39 UTC, ant1quar commented on source/index.html
> +              </li>
иконок нет

2021-03-28 17:48 UTC, ant1quar commented on source/index.html
> +      </a>
хотя, там по заданию нужно только мобильную верстку сделать.

2021-03-29 00:30 UTC, LianaBazhenova commented on source/index.html
> +          <ul class="main-nav__list">
у меня на других блоках таким же образом обертки , делала по демке, как в лекции. 
убрать у других тоже ? я не совсем поняла когда мы можем добавить класс к блоку, а когда мы должны обернуть блок дивом. в лекции сказали смотреть по ситуации.

2021-03-29 00:30 UTC, LianaBazhenova commented on source/index.html
> +        <div class="hero-header__wrapper">
я думала бэкграундом да)

2021-03-29 00:32 UTC, LianaBazhenova commented on source/index.html
> +            </div>
ахах )

2021-04-01 07:30 UTC, ant1quar requested changes

2021-04-01 07:31 UTC, merged